AWSTemplateFormatVersion: '2010-09-09'
Description: cf tutorial stack
Parameters:
  Prefix:
    Type: Strign
    Default: testing
    Description: Prefix Name
    
  ServiceName:
    Type: String
    Default: cf-tutorial

# AWSで使うサービスを定義していく
Resources:
  EC2SecurityGroupApp:
    Type: "AWS::EC2::SecurityGroup" # 配置するリソース。
    Properties: # 
      GroupName: !Sub "${Prefix}_${ServiceName}_app" # Parametersから参照
      GroupDescription: "Web server security group"
      VpcId:
        "{your VPCID}"
      SecurityGroupIngress:
        - IpProtocolL: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: !Sub "${Prefix}_${ServiceName}_app"

  Ec2InstanceServer:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      ImageId: "ami-06cd52961ce9f0d85"
      InstanceType: "t2.micro"
      KeyName: "keypair"
      SecurytyGroupIds:
        - !Ref Ec2SecurityGroupApp
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Eds:
            VolumeSize: 8
            VolumeTyoe: gp2
      Tags:
        - Key: Name
          Value: !Sub "${Prefix}_${ServieName}_app"
Outputs:
